<?php

namespace App\Constants;

class UserActivityConstants
{
    const PROFILE_ACTIVITY = "PROFILE_ACTIVITY";
    const LOCATION_ACTIVITY = "LOCATION_ACTIVITY";
    const PRICING_ACTIVITY = "PRICING_ACTIVITY";
    const ORDER_ACTIVITY = "ORDER_ACTIVITY";
    const VEHICLE_ACTIVITY = "VEHICLE_ACTIVITY";
    const FAQ_ACTIVITY = "FAQ_ACTIVITY";
}
