<?php

namespace App\Constants;

class UserActivityConstants
{
    const PROFILE_ACTIVITY = "PROFILE_ACTIVITY";
    const LOCATION_ACTIVITY = "LOCATION_ACTIVITY";
    const PRICING_ACTIVITY = "PRICING_ACTIVITY";
    const ORDER_ACTIVITY = "ORDER_ACTIVITY";
    const VEHICLE_ACTIVITY = "VEHICLE_ACTIVITY";
    const VENDOR_ACTIVITY = "VENDOR_ACTIVITY";
    const ITEM_ACTIVITY = "ITEM_ACTIVITY";
    const FAQ_ACTIVITY = "FAQ_ACTIVITY";
    const FINANCE_ACTIVITY = "FINANCE_ACTIVITY";
    const STATE_ACTIVITY = "STATE_ACTIVITY";
    const MEMO_ACTIVITY = "MEMO_ACTIVITY";
}
